# Route to create new flat resource
create:
    path: /flats
    controller: App\Controller\RestController::createFlat
    methods:  [POST]

# Route to get a list of all flat resources
list:
    path: /flats
    controller: App\Controller\RestController::getList
    methods:  [GET]

# Route to get the details of a single flat resource
details:
    path: /flats/{id}
    controller: App\Controller\RestController::getFlat
    methods:  [GET]
    requirements:
        id: '\d+'

# Route to update a single flat resource
update:
    path: /flats/{id}
    controller: App\Controller\RestController::updateFlat
    methods:  [PUT]
    requirements:
        id: '\d+'

# Route to delete a single flat resource
delete:
    path: /flats/{id}
    controller: App\Controller\RestController::deleteFlat
    methods:  [DELETE]
    requirements:
        id: '\d+'
